services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9001:9000"   # S3 API endpoint
    #  - "9002:9001"   # Web console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: strongpassword
    volumes:
       - minio_data:/data 
volumes:
  minio_data:
