services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: 'Australia/Queensland'
      FTLCONF_webserver_api_password: 'runcornschool'
      FTLCONF_dns_listeningMode: 'all'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns: 
      - 1.1.1.1
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    labels:
      - "traefik.enable=true"
      # Update the following for Pi-hole, not Grafana
      - "traefik.http.routers.pihole.rule=Host(`ddns.lurking.site`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=cloudflare"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    networks:
      - frontend

networks:
  frontend:
    external: true
