services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    networks:
      docker-vlan-01:
        ipv4_address: 172.20.0.3
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    dns: 
      - 8.8.8.8
      - 1.1.1.1
networks:
  docker-vlan-01:
    external: true
