---
services:
  nginx:
    image: nginx:1.25.5-alpine
    container_name: nginx-demo-1
    ports:
      - "8080:80"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - site_data:/site_data
      - /site_data/html:/usr/share/ngnix/html
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true

volumes:
  site_data:
    external: true
