---
services:
  nginx:
    image: nginx:1.25.5-alpine
    container_name: nginx-demo-1
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server_site:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-demo-1-https.entrypoints=websecure"
      - "traefik.http.routers.nginx-demo-1-https.rule=Host(`nginx-demo-1.lurking.site`)"
      - "traefik.http.routers.nginx-demo-1-https.tls=true"
      - "traefik.http.routers.nginx-demo-1-https.tls.certresolver=cloudflare"
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true


