version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    restart: always
    environment:
      LDAP_ORGANISATION: "Homelab"
      LDAP_DOMAIN: "corp.lurking.site"
      LDAP_ADMIN_PASSWORD: "runcornschool"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "5656:80"
    depends_on:
      - openldap

volumes:
  openldap_data:
  openldap_config:
