# To see all available options, please visit the docs:
# https://docs.digpangolin.com/self-host/advanced/config-file 

gerbil:
    start_port: 51820
    base_endpoint: "pangolin.lurking.site"

app:
    dashboard_url: "https://pangolin.lurking.site"
    log_level: "info"
    telemetry:
        anonymous_usage: true

domains:
    domain1:
        base_domain: "lurking.site"
        cert_resolver: "cloudflare"

server:
    secret: "vKFgOXLFTo6goXzybJqDOTnRP7kCfG57"
    cors:
        origins: ["https://pangolin.lurking.site"]
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        allowed_headers: ["X-CSRF-Token", "Content-Type"]
        credentials: false

flags:
    require_email_verification: false
    disable_signup_without_invite: true
    disable_user_create_org: false
    allow_raw_resources: true
